name: NoticiasDiarias

on:
  schedule:
    - cron: '0 6 * * *'  # Cada día a las 6 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install feedparser

      - name: Ejecutar script de scraping
        run: python generar_noticias.py

      - name: Subir cambios
        run: |
          git config --global user.name 'Auto Bot'
          git config --global user.email 'bot@infotal24.com'
          git add .
          git commit -m "Noticias actualizadas"
          git push
