name: NoticiasDiarias

on:
  schedule:
    - cron: '0 6 * * *'  # Cada día a las 6 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install feedparser

      - name: Ejecutar script de scraping
        run: python generar_noticias.py

      - name: Mostrar estado git
        run: git status

      - name: Subir cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Auto Bot'
          git config --global user.email 'bot@infotal24.com'
          git add .
          git diff --cached --quiet || git commit -m "Noticias actualizadas"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/AntonioSysPro/InfoTal-24.git main
